name: Deploy Firebase

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install functions deps
        working-directory: functions
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Firebase info
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase --version
          firebase projects:list --project moldajes-retorno || true

      - name: Deploy Functions (debug)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --non-interactive --only functions --project moldajes-retorno --debug

      - name: Deploy Hosting (debug)
        if: always()
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --non-interactive --only hosting --project moldajes-retorno --debug
